apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  avoidBuggyIPs: true
  addresses:
    - 10.1.64.0/24
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: pfsense
  namespace: metallb-system
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 10.1.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: first-pool-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool