---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bastion-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bastion-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bastion-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bastion-cluster-role
subjects:
  - kind: ServiceAccount
    name: bastion-sa
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      serviceAccountName: bastion-sa
      containers:
        - name: bastion
          image: bitnami/kubectl:latest
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"